Set ncclient version with fix for DSSKey (#91)
ncclient 0.7.0 has the fix for DSSKey that was recently removed from the
latest version of Paramiko (4.0.0). This will avoid the jobs from
failing with error
```
AttributeError: module 'paramiko' has no attribute 'DSSKey'
```

Fix LVM thin pool issue

clean registry when disk util over 40 percent